export const SAVE_ACCESSTOKEN = "SAVE_ACCESSTOKEN";
export const SAVE_EMPLOYEE = "SAVE_EMPLOYEE";
export const SAVE_AUTHENTICATE = "SAVE_AUTHENTICATE";
export const SAVE_BOOKER_BOOKING_DETAILS = "SAVE_BOOKER_BOOKING_DETAILS";
export const UPDATE_STATUS_BOOKER_DECLINE = "UPDATE_STATUS_BOOKER_DECLINE";
export const SAVE_ERROR_MESSAGE = "SAVE_ERROR_MESSAGE";
export const SAVE_PAGE_NAME = "SAVE_PAGE_NAME";



export const ROLE = {
    SUPER_ADMIN: "SuperAdmin",
    ADMIN: "Admin",
    MEMBER: "Member"
}