export const SAVE_BOOKING_INFOR = "SAVE_BOOKING_INFOR";
export const SAVE_BOOKER = "SAVE_BOOKER";
export const SAVE_BOOKING_DETAILS = "SAVE_BOOKING_DETAILS";
export const SAVE_DRIVER_CARS = "SAVE_DRIVER_CARS";
export const UPDATE_DRIVER_CAR = "UPDATE_DRIVER_CAR";
export const SAVE_TRIP_INFORMATION = "SAVE_TRIP_INFORMATION";