export const SAVE_PERSON_BOOKS = "SAVE_PERSON_BOOKS";
export const SAVE_CARS = "SAVE_BKC_CARS";
export const SAVE_DRIVERS = "SAVE_BKC_DRIVERS";
export const SAVE_DETAIL_PERSON_IN_CAR = "SAVE_DETAIL_PERSON_IN_CAR";

export const SAVE_BKC_INFORS = "SAVE_BKC_INFORS";
export const SAVE_BKC_DETAILS = "SAVE_BKC_DETAILS";
