export const SET_TICKET_INFORMATION = "SET_TICKET_INFORMATION";
export const SET_TICKET_DETAIL = "SET_TICKET_DETAIL";
export const SET_LOCATION = "SET_LOCATION";
export const TOGGLE_MODAL_ADD_LOCATION = "TOGGLE_MODAL_ADD_LOCATION";